### PR TITLE
Updated Specifications and diagrams

### PR DESCRIPTION
**Pull request by ghost**
Updated Specifications and diagrams

### CODE REVIEW

**Review by JonathanPartain — CHANGES_REQUESTED** [review]
Don't make all the titles bold and the same size, looks boring and not very nice imo

**Comment by yazan086** [comment]
All sentences should start with a capital letter

**Comment by ghost** [comment]
@JonathanPartain @yazan086  Your requested changes were made

**Review by JonathanPartain — CHANGES_REQUESTED** [review]
Could all sentences in the third column please start with a capital letter?

**Comment by ghost** [comment]
@JonathanPartain your latest changes requested were made

**Pull request merged**
